server:
  port: 8101

spring:
  application:
    name: cloud-order-consumer-service
  cloud:
    consul:
      host: 172.16.133.132
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        register: true
        prefer-ip-address: true