spring:
  application:
    name: cloud-payment-provider-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.16.133.132:3306/db2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: ozone

mybatis-plus:
  type-aliases-package: com.ozixue.entity
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

---
server:
  port: 8001
spring:
  profiles: payment1

---
server:
  port: 8002
spring:
  profiles: payment2