server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lirubao/cloud-2020.git
          # 搜索目录
          search-paths:
            # - cloud-2020
            - cloud-config
          # 读取分支
      label: OpenFeign
  # RabbitMQ
  rabbitmq:
    host: 172.16.133.132
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:7001/eureka,http://eureka2:7002/eureka
# RabbitMQ相关配置, 暴露bus刷新配置的端点
management:
  endpoints:  # 暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'
