server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh           # 路由ID, 没有固定规则但要求唯一, 建议配合服务名
          uri: http://localhost:8001  #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/find/**   #断言, 路径相匹配的进行路由

        - id: payment_routh2          # 路由ID, 没有固定规则但要求唯一, 建议配合服务名
          uri: http://localhost:8001  #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/discovery   #断言, 路径相匹配的进行路由

eureka:
  instance:
    hostname: ${spring.application.name}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka1:7001/eureka,http://eureka2:7002/eureka