spring:
  application:
    name: eureka-server

eureka:
  server:
    # 关闭自我保护模式
    enable-self-preservation: false
  instance:
    hostname: eureka
    lease-renewal-interval-in-seconds: 10
    #  client:
    # false 表示不向注册中心注册自己
#    register-with-eureka: false
#    fetch-registry: false
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
# 启动参数 --spring.profiles.active=eureka1
---
spring:
  profiles: eureka1

server:
  port: 7001

eureka:
  instance:
    hostname: eureka1
  client:
    service-url:
      defaultZone: http://eureka2:7002/eureka

---
spring:
  profiles: eureka2

server:
  port: 7002

eureka:
  instance:
    hostname: eureka2
  client:
    service-url:
      defaultZone: http://eureka1:7001/eureka